#online shop 版本控制
theOnlineShop:
  Name: Online Shop
  Version: 1.0.0
  Github: https://github.com/Tommyczc/theOnlineShop
  Copyright: 2022

#服务器配置
server:
  #端口
  port: 8082
  tomcat:
    uri-encoding: UTF-8

spring:
  #thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    check-template: true
    check-template-location: true

  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/theonlineshop?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 

  servlet:
    multipart:
      # 最大上传文件
      max-file-size: 10MB
      # 最大请求文件
      max-request-size: 20MB

  mail:
    host: smtp.qq.com    #邮箱服务器地址
    username: 870667475@qq.com   #邮箱账号
    password: fbqhtvshhonkbeif       #邮箱授权码
    default-encoding: utf-8    #默认编码

  redis:
    host: localhost
    port: 6379
    password: 1234

#  mvc:
#    static-path-pattern: /static/**


mybatis:
  # 实体类包名
  typeAliasesPackage: com.theOnlineShop.domain
  # mapper文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # mybatis配置文件
  configLocation: classpath:Mybatis/MybatisConfig.xml



#自己写的配置
personal:
  #加密密钥
  EncryptionKey:
    aes-key: 7w6trwyug23t678g

  #邮件发件人
  mail:
    #验证码过期时间(分钟)
    expiredTime: 5
    fromMail:
      fromAddress: 870667475@qq.com

  #权限角色数量 -1默认该权限角色数量为 无限
  role:
    #超级管理员数量
    superAdminNum: 1
    #管理员数量
    adminNum: 5
    #用户
    userNum: -1

  #静态文件路径映射
  fileStore:
    #Windows本地文件地址配置
    windowsStaticFileUrl: C:/uploadDoc/
    #Linux本地文件地址配置
    linuxStaticFileUrl: /usr/nessystem/staticFiles/
    #映射路径
    mappingAddress: /staticDocument

